apiVersion: v1
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire"
      log_level = "ERROR"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = "/run/spire/sockets/agent/agent.sock"
      admin_socket_path = "/run/spire/sockets/admin.sock"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "spiffe.cilium"
      authorized_delegates = [
        "spiffe://spiffe.cilium/cilium-agent",
      ]
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "default"
        }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = true
        }
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "4251"
      live_path = "/live"
      ready_path = "/ready"
    }
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: cilium-spire
