apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: azure-acme-issuer
  name: hubble
  namespace: kube-system
spec:
  ingressClassName: haproxy
  rules:
    - host: hubble.cluster.anderwerse.de
      http:
        paths:
          - backend:
              service:
                name: hubble
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - hubble.cluster.anderwerse.de
      secretName: hubble-tls
