apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app: kube-prometheus-alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.6.9
    chart: kube-prometheus-stack-81.6.9
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-alertmanager
  namespace: monitoring
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - alertmanager
                - key: alertmanager
                  operator: In
                  values:
                    - kube-prometheus-alertmanager
            topologyKey: kubernetes.io/hostname
          weight: 100
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector: {}
  automountServiceAccountToken: true
  externalUrl: http://kube-prometheus-alertmanager.monitoring:9093
  image: quay.io/prometheus/alertmanager:v0.31.1
  imagePullPolicy: IfNotPresent
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMetadata:
    labels:
      haproxy/egress: allow
  portName: http-web
  replicas: 2
  retention: 120h
  routePrefix: /
  secrets:
    - alertmanager-acs-secret
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: kube-prometheus-alertmanager
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 2Gi
        storageClassName: longhorn
  version: v0.31.1
