apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-prometheus-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.6.2
    chart: kube-prometheus-stack-81.6.2
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-prometheus-prometheus
subjects:
  - kind: ServiceAccount
    name: kube-prometheus-prometheus
    namespace: monitoring
