apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: kube-prometheus-kube-proxy
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.4.2
    chart: kube-prometheus-stack-81.4.2
    heritage: Helm
    k8s-app: kube-proxy
    release: kube-prometheus-stack
  name: kube-prometheus-kube-proxy
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.178.201
      - ip: 192.168.178.203
      - ip: 192.168.178.204
      - ip: 192.168.178.205
    ports:
      - name: http-metrics
        port: 10249
        protocol: TCP
