apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: kube-prometheus-kube-controller-manager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.6.1
    chart: kube-prometheus-stack-81.6.1
    heritage: Helm
    k8s-app: kube-controller-manager
    release: kube-prometheus-stack
  name: kube-prometheus-kube-controller-manager
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.178.201
      - ip: 192.168.178.203
      - ip: 192.168.178.205
    ports:
      - name: http-metrics
        port: 10257
        protocol: TCP
