apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: kube-prometheus-kube-scheduler
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 82.0.0
    chart: kube-prometheus-stack-82.0.0
    heritage: Helm
    k8s-app: kube-scheduler
    release: kube-prometheus-stack
  name: kube-prometheus-kube-scheduler
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.178.201
      - ip: 192.168.178.203
      - ip: 192.168.178.205
    ports:
      - name: http-metrics
        port: 10259
        protocol: TCP
