apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: kube-prometheus-admission-patch
    app.kubernetes.io/component: prometheus-operator-webhook
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.6.3
    chart: kube-prometheus-stack-81.6.3
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-admission-patch
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: kube-prometheus-admission-patch
        app.kubernetes.io/component: prometheus-operator-webhook
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-prometheus-prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 81.6.3
        chart: kube-prometheus-stack-81.6.3
        heritage: Helm
        release: kube-prometheus-stack
      name: kube-prometheus-admission-patch
    spec:
      containers:
        - args:
            - patch
            - --webhook-name=kube-prometheus-admission
            - --namespace=monitoring
            - --secret-name=kube-prometheus-admission
            - --patch-failure-policy=
          image: ghcr.io/jkroepke/kube-webhook-certgen:1.7.6
          imagePullPolicy: IfNotPresent
          name: patch
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: kube-prometheus-admission
  ttlSecondsAfterFinished: 60
