apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.3.1
    helm.sh/chart: grafana-10.5.10
  name: kube-prometheus-stack-grafana-test
  namespace: monitoring
spec:
  containers:
    - command:
        - /opt/bats/bin/bats
        - -t
        - /tests/run.sh
      image: docker.io/bats/bats:v1.4.1
      imagePullPolicy: IfNotPresent
      name: kube-prometheus-stack-test
      volumeMounts:
        - mountPath: /tests
          name: tests
          readOnly: true
  restartPolicy: Never
  serviceAccountName: kube-prometheus-stack-grafana-test
  volumes:
    - configMap:
        name: kube-prometheus-stack-grafana-test
      name: tests
