apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 79.12.0
    chart: kube-prometheus-stack-79.12.0
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-kubernetes-system-kube-proxy
  namespace: monitoring
spec:
  groups:
    - name: kubernetes-system-kube-proxy
      rules:
        - alert: KubeProxyDown
          annotations:
            description: KubeProxy has disappeared from Prometheus target discovery.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeproxydown
            summary: Target disappeared from Prometheus target discovery.
          expr: absent(up{job="kube-proxy"})
          for: 15m
          labels:
            severity: critical
