apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.3.3
    helm.sh/chart: grafana-11.1.5
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: grafana
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  type: ClusterIP
