apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-kube-etcd
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.6.0
    chart: kube-prometheus-stack-81.6.0
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-kube-etcd
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: kube-prometheus-kube-etcd
      release: kube-prometheus-stack
