apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.6.3
    chart: kube-prometheus-stack-81.6.3
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-prometheus
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: http-web
    - path: /metrics
      port: reloader-web
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: kube-prometheus-prometheus
      release: kube-prometheus-stack
      self-monitor: "true"
