apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-kube-scheduler
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 80.9.2
    chart: kube-prometheus-stack-80.9.2
    heritage: Helm
    jobLabel: kube-scheduler
    release: kube-prometheus-stack
  name: kube-prometheus-kube-scheduler
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10259
      protocol: TCP
      targetPort: 10259
  selector:
    component: kube-scheduler
  type: ClusterIP
