apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.6.5
    chart: kube-prometheus-stack-81.6.5
    heritage: Helm
    release: kube-prometheus-stack
    self-monitor: "true"
  name: kube-prometheus-prometheus
  namespace: monitoring
spec:
  ports:
    - name: http-web
      port: 9090
      targetPort: 9090
    - appProtocol: http
      name: reloader-web
      port: 8080
      targetPort: reloader-web
  publishNotReadyAddresses: false
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: kube-prometheus-prometheus
  sessionAffinity: None
  type: ClusterIP
