apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.6.9
    chart: kube-prometheus-stack-81.6.9
    heritage: Helm
    release: kube-prometheus-stack
    self-monitor: "true"
  name: kube-prometheus-alertmanager
  namespace: monitoring
spec:
  ports:
    - name: http-web
      port: 9093
      protocol: TCP
      targetPort: 9093
    - appProtocol: http
      name: reloader-web
      port: 8080
      targetPort: reloader-web
  selector:
    alertmanager: kube-prometheus-alertmanager
    app.kubernetes.io/name: alertmanager
  sessionAffinity: None
  type: ClusterIP
