apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-kube-controller-manager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.6.1
    chart: kube-prometheus-stack-81.6.1
    heritage: Helm
    jobLabel: kube-controller-manager
    release: kube-prometheus-stack
  name: kube-prometheus-kube-controller-manager
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10257
      protocol: TCP
      targetPort: 10257
  type: ClusterIP
