apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.2.1
    helm.sh/chart: grafana-10.1.4
  name: kube-prometheus-stack-grafana
  namespace: monitoring
