apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: kube-prometheus-alertmanager
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 81.6.0
    chart: kube-prometheus-stack-81.6.0
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-alertmanager
  namespace: monitoring
