apiVersion: v1
data:
  aliasgroup1: https://nextcloud.anderwerse.de:443
  extra_params: --o:storage.wopi.host=nextcloud\.anderwerse\.de --o:ssl.enable=false --o:ssl.termination=true
kind: ConfigMap
metadata:
  annotations:
    confighash: config-a0b855858a4b551aaed24446d7f9b1f3
  labels:
    app.kubernetes.io/instance: collabora
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: collabora-online
    app.kubernetes.io/version: 25.04.8.1.1
    helm.sh/chart: collabora-online-1.1.54
  name: collabora-collabora-online
  namespace: nextcloud
