apiVersion: v1
data:
  aliasgroup1: https://collabora.anderwerse.de:443
  aliasgroup2: https://collabora.anderwerse.de:8443
  extra_params: --o:ssl.enable=false --o:ssl.termination=true
kind: ConfigMap
metadata:
  annotations:
    confighash: config-1f0c0a47ea5d68b6309aca01aa5534b5
  labels:
    app.kubernetes.io/instance: collabora
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: collabora-online
    app.kubernetes.io/version: 25.04.8.1.1
    helm.sh/chart: collabora-online-1.1.54
  name: collabora-collabora-online
  namespace: nextcloud
