apiVersion: v1
data:
  aliasgroup1: https://nextcloud.anderwerse.de:443
  extra_params: --o:ssl.enable=false --o:ssl.termination=true
kind: ConfigMap
metadata:
  annotations:
    confighash: config-83f632b625409bb222473821ff2757ef
  labels:
    app.kubernetes.io/instance: collabora
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: collabora-online
    app.kubernetes.io/version: 25.04.8.3.1
    helm.sh/chart: collabora-online-1.1.56
  name: collabora-collabora-online
  namespace: nextcloud
