apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-route
  namespace: nextcloud
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nextcloud.anderwerse.de`)
      middlewares:
        - name: nextcloud-hsts-middleware
          namespace: nextcloud
      services:
        - name: nextcloud
          namespace: nextcloud
          port: 8080
  tls:
    secretName: nextcloud-tls-certificate
