apiVersion: v1
data:
  default-resource.yaml: |-
    backup-target: azblob://backup@core.windows.net/
    backup-target-credential-secret: longhorn-azblob-secret
    backupstore-poll-interval: 172800
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.11.0
    helm.sh/chart: longhorn-1.11.0
  name: longhorn-default-resource
  namespace: longhorn-system
