apiVersion: v1
data:
  default-setting.yaml: |-
    replica-auto-balance: "best-effort"
    storage-over-provisioning-percentage: "75"
    priority-class: "longhorn-critical"
    disable-revision-counter: "{\"v1\":\"true\"}"
    concurrent-automatic-engine-upgrade-per-node-limit: "1"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.10.1
    helm.sh/chart: longhorn-1.10.1
  name: longhorn-default-setting
  namespace: longhorn-system
