apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: kubernetes-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 3.2.5
    helm.sh/chart: kubernetes-ingress-1.48.0
  name: kubernetes-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-ingress
subjects:
  - kind: ServiceAccount
    name: kubernetes-ingress
    namespace: haproxy
