apiVersion: v1
data:
  haproxy.cfg: |2


    global
      log stdout format raw local0
      maxconn 1024

    defaults
      log global
      timeout client 60s
      timeout connect 60s
      timeout server 60s
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: 3.2.9
    helm.sh/chart: haproxy-1.27.0
  name: haproxy
  namespace: haproxy
