apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: 3.2.9
    helm.sh/chart: haproxy-1.27.0
  name: haproxy
  namespace: haproxy
spec:
  minReadySeconds: 0
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: haproxy
      app.kubernetes.io/name: haproxy
  template:
    metadata:
      annotations:
        checksum/environment: 2de53f34dac196fa1026ba36b309bac8ed986bf2e8b74878c0b0b3aa809726c6
      labels:
        app.kubernetes.io/instance: haproxy
        app.kubernetes.io/name: haproxy
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - -f
            - /usr/local/etc/haproxy/haproxy.cfg
          image: haproxytech/haproxy-alpine:3.2.9
          imagePullPolicy: IfNotPresent
          name: haproxy
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 1024
              name: stat
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
          volumeMounts:
            - mountPath: /usr/local/etc/haproxy
              name: haproxy-config
      dnsPolicy: ClusterFirst
      securityContext: {}
      serviceAccountName: haproxy
      terminationGracePeriodSeconds: 60
      volumes:
        - configMap:
            name: haproxy
          name: haproxy-config
