apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    helm.sh/hook: post-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/instance: kubernetes-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-ingress-proxy
    app.kubernetes.io/version: 3.2.5
    helm.sh/chart: kubernetes-ingress-1.48.0
  name: kubernetes-ingress-crdjob-1
  namespace: haproxy
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kubernetes-ingress
        app.kubernetes.io/name: kubernetes-ingress-proxy
    spec:
      containers:
        - command:
            - /haproxy-ingress-controller
            - --job-check-crd
          image: docker.io/haproxytech/kubernetes-ingress:3.2.5
          imagePullPolicy: IfNotPresent
          name: crd
          resources:
            requests:
              cpu: 250m
              memory: 400Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: kubernetes-ingress
  ttlSecondsAfterFinished: 600
