apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: kubernetes-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 3.2.5
    cilium/ippool: haproxy
    cilium/l2: announce
    helm.sh/chart: kubernetes-ingress-1.48.0
  name: kubernetes-ingress
  namespace: haproxy
spec:
  ports:
    - appProtocol: http
      name: http
      port: 80
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      port: 443
      protocol: TCP
      targetPort: https
    - appProtocol: https
      name: quic
      port: 443
      protocol: UDP
      targetPort: quic
    - name: stat
      port: 1024
      protocol: TCP
      targetPort: stat
    - name: admin
      port: 6060
      protocol: TCP
      targetPort: admin
  selector:
    app.kubernetes.io/instance: kubernetes-ingress
    app.kubernetes.io/name: kubernetes-ingress
  type: LoadBalancer
