apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/sharing-cross-namespace: '*'
    lbipam.cilium.io/sharing-key: default-ippool
  labels:
    app.kubernetes.io/instance: kubernetes-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/role: entrypoint
    app.kubernetes.io/version: 3.2.4
    helm.sh/chart: kubernetes-ingress-1.47.4
  name: kubernetes-ingress
  namespace: haproxy
spec:
  ports:
    - appProtocol: http
      name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      port: 8443
      protocol: TCP
      targetPort: https
    - appProtocol: https
      name: quic
      port: 8443
      protocol: UDP
      targetPort: quic
    - name: stat
      port: 1024
      protocol: TCP
      targetPort: stat
    - name: admin
      port: 6060
      protocol: TCP
      targetPort: admin
  selector:
    app.kubernetes.io/instance: kubernetes-ingress
    app.kubernetes.io/name: kubernetes-ingress
  type: LoadBalancer
