apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: kubernetes-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 3.2.4
    helm.sh/chart: kubernetes-ingress-1.47.4
  name: kubernetes-ingress
  namespace: haproxy
