apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: traefik-loadbalancer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    app.kubernetes.io/role: entrypoint
    helm.sh/chart: traefik-38.0.2
  name: traefik-loadbalancer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-loadbalancer
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: loadbalancer
