apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  labels:
    app.kubernetes.io/instance: traefik-loadbalancer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    app.kubernetes.io/role: entrypoint
    helm.sh/chart: traefik-38.0.2
  name: traefik
spec:
  controller: traefik.io/ingress-controller
