apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/sharing-cross-namespace: '*'
    lbipam.cilium.io/sharing-key: default-ippool
  labels:
    app.kubernetes.io/instance: traefik-loadbalancer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    app.kubernetes.io/role: entrypoint
    helm.sh/chart: traefik-39.0.0
  name: traefik
  namespace: loadbalancer
spec:
  ports:
    - name: tcp-port-21115
      port: 21115
      protocol: TCP
      targetPort: tcp-port-21115
    - name: tcp-port-21116
      port: 21116
      protocol: TCP
      targetPort: tcp-port-21116
    - name: tcp-port-21117
      port: 21117
      protocol: TCP
      targetPort: tcp-port-21117
    - name: udp-port-21116
      port: 21116
      protocol: UDP
      targetPort: udp-port-21116
  selector:
    app.kubernetes.io/instance: traefik-loadbalancer
    app.kubernetes.io/name: traefik
  type: LoadBalancer
