apiVersion: v1
data:
  applicationsetcontroller.enable.leader.election: "false"
  applicationsetcontroller.log.format: text
  applicationsetcontroller.log.level: info
  commitserver.log.format: text
  commitserver.log.level: info
  controller.log.format: text
  controller.log.level: info
  dexserver.log.format: text
  dexserver.log.level: info
  notificationscontroller.log.format: text
  notificationscontroller.log.level: info
  redis.server: argocd-redis:6379
  repo.server: argocd-repo-server:8081
  reposerver.log.format: text
  reposerver.log.level: info
  server.dex.server: https://argocd-dex-server:5556
  server.dex.server.strict.tls: "false"
  server.insecure: "true"
  server.log.format: text
  server.log.level: info
  server.repo.server.strict.tls: "false"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.2.3
    helm.sh/chart: argo-cd-9.2.3
  name: argocd-cmd-params-cm
  namespace: argocd
