apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-gpg-keys-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.2.0
    helm.sh/chart: argo-cd-9.1.0
  name: argocd-gpg-keys-cm
  namespace: argocd
