apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
spec:
  destination:
    namespace: haproxy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./haproxy
    repoURL: https://github.com/aserowy/dots.git
    targetRevision: homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
