apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devices
  namespace: argocd
spec:
  destination:
    namespace: devices
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /spec/names/categories
      kind: CustomResourceDefinition
  project: default
  source:
    path: ./devices
    repoURL: https://github.com/aserowy/dots.git
    targetRevision: homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
