apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: sops-secrets-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sops-secrets-operator
    app.kubernetes.io/version: 0.17.3
    helm.sh/chart: sops-secrets-operator-0.24.1
  name: sops-secrets-operator
  namespace: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sops-secrets-operator
      app.kubernetes.io/name: sops-secrets-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: sops-secrets-operator
      labels:
        app.kubernetes.io/instance: sops-secrets-operator
        app.kubernetes.io/name: sops-secrets-operator
        control-plane: controller-sops-secrets-operator
    spec:
      containers:
        - args:
            - -health-probe-bind-address=:8081
            - -leader-elect
            - -requeue-decrypt-after=5
            - -zap-devel=false
            - -zap-encoder=json
            - -zap-log-level=info
            - -zap-stacktrace-level=error
            - -zap-time-encoding=iso8601
          command:
            - /usr/local/bin/manager
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SOPS_AGE_KEY_FILE
              value: /var/lib/sops/age/key.txt
          image: quay.io/isindir/sops-secrets-operator:0.17.3
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: sops-secrets-operator
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/sops/age
              name: keys
              readOnly: true
      serviceAccountName: sops-secrets-operator
      volumes:
        - name: keys
          secret:
            secretName: age-keys
